### ISSUE TITLE
Use API for retrieving contact ID by contact hash

### ISSUE THREAD

**Issue by jensschuppe** [systopia/de.systopia.selfservice#1]
Is there any reason why the contact is not being identified using the API in `CRM_Selfservice_HashLinks::getContactIdFromHash()` instead of using CiviCRM core code?

**Comment by bjendres** [comment]
> Is there any reason why the contact is not being identified using the API in `CRM_Selfservice_HashLinks::getContactIdFromHash()` instead of using CiviCRM core code?

I'm not sure what  core code you mean? We're using our own extended hash links here, not (just) the core one. See here:
https://github.com/systopia/de.systopia.selfservice/blob/f0d6eb120bc475746b1d4774f25822df1bc375fe/CRM/Selfservice/HashLinks.php#L81-L83

**Comment by jensschuppe** [comment]
But why is the hash being prefixed with the contact ID in the first place? Contacts can be identified using the `Contact.getsingle` API with the contact hash as the only parameter. Also, retrieving/generating a hash for a contact can be done using the `Contact.getsingle` API as well. Am I missing something?

**Comment by bjendres** [comment]
There was a good reason for this at the time...why does it matter?

**Comment by jensschuppe** [comment]
When using [CiviMRF Webform](https://github.com/civimrf/cmrf_core/) for sending/receiving values for contact hashes, you can not use standard CiviCRM APIs, e.g. for retrieving default values via `Contact.getsingle` with the hash.

The `Selfservice.getcontact` API only returns the contact ID, so you can't use this API for retrieving contact values either.

**Comment by bjendres** [comment]
> The `Selfservice.getcontact` API only returns the contact ID, so you can't use this API for retrieving contact values either.

We could extend `Selfservice.getcontact` API to return requested contact fields, but what's the problem with doing two stages? Plus you can create a FormProcessor if you're restricted to one API call, e.g. for prefill.

**Comment by jensschuppe** [comment]
I'm just wondering what the purpose of the extra prefix was, since it's causing extra steps that wouldn't be necessary without it.

Since you said there was a reason, this question is sufficiently answered.
